-- Datos reproducibles para EduAndes.
-- Ejecutar despues del primer arranque, cuando Hibernate ya creo las tablas.
-- La limpieza permite repetir los casos CP01-CP14 con los mismos identificadores.

DELETE FROM detalle_matriculas;
DELETE FROM matriculas;
DELETE FROM cursos;
DELETE FROM estudiantes;
DELETE FROM carreras;

INSERT INTO carreras (id, nombre, descripcion, estado, fecha_creacion)
VALUES (1, 'Ingeniería de Sistemas', 'EP Ingeniería de Sistemas', 1, CURRENT_TIMESTAMP);
INSERT INTO carreras (id, nombre, descripcion, estado, fecha_creacion)
VALUES (2, 'Ingeniería Civil', 'EP Ingeniería Civil', 1, CURRENT_TIMESTAMP);
INSERT INTO carreras (id, nombre, descripcion, estado, fecha_creacion)
VALUES (3, 'Arquitectura', 'EP Arquitectura y Urbanismo', 1, CURRENT_TIMESTAMP);

-- Ingeniería de Sistemas: siete cursos activos; IS404 no tiene vacantes.
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (1, 'IS401', 'Lenguaje de Programación II', 3, 4, 30, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (2, 'IS402', 'Base de Datos II', 4, 4, 25, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (3, 'IS403', 'Ingeniería de Requisitos', 3, 4, 2, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (4, 'IS404', 'Estadística Aplicada', 3, 4, 0, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (5, 'IS501', 'Arquitectura de Software', 4, 5, 20, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (6, 'IS502', 'Sistemas Operativos', 4, 5, 15, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (7, 'IS503', 'Redes de Computadoras', 4, 5, 20, 1, 1, CURRENT_TIMESTAMP);

-- Ingeniería Civil: IC402 es el segundo curso sin vacantes.
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (8, 'IC401', 'Mecánica de Suelos', 4, 4, 30, 1, 2, CURRENT_TIMESTAMP);
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (9, 'IC402', 'Resistencia de Materiales', 4, 4, 0, 1, 2, CURRENT_TIMESTAMP);
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (10, 'IC501', 'Diseño de Estructuras', 5, 5, 18, 1, 2, CURRENT_TIMESTAMP);

-- Arquitectura: AR402 es el curso inactivo solicitado.
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (11, 'AR401', 'Taller de Diseño IV', 6, 4, 15, 1, 3, CURRENT_TIMESTAMP);
INSERT INTO cursos (id, codigo, nombre, creditos, ciclo, vacantes, estado, carrera_id, fecha_creacion)
VALUES (12, 'AR402', 'Urbanismo II', 4, 4, 12, 0, 3, CURRENT_TIMESTAMP);

INSERT INTO estudiantes (id, codigo, dni, nombres, apellidos, email, estado, carrera_id, fecha_creacion)
VALUES (1, '202410001', '71234567', 'Ana Lucía', 'Quispe Mamani', 'ana.quispe@upeu.edu.pe', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO estudiantes (id, codigo, dni, nombres, apellidos, email, estado, carrera_id, fecha_creacion)
VALUES (2, '202410002', '72345678', 'Jorge Luis', 'Condori Apaza', 'jorge.condori@upeu.edu.pe', 1, 1, CURRENT_TIMESTAMP);
INSERT INTO estudiantes (id, codigo, dni, nombres, apellidos, email, estado, carrera_id, fecha_creacion)
VALUES (3, '202410003', '73456789', 'María Elena', 'Huamán Torres', 'maria.huaman@upeu.edu.pe', 1, 2, CURRENT_TIMESTAMP);
INSERT INTO estudiantes (id, codigo, dni, nombres, apellidos, email, estado, carrera_id, fecha_creacion)
VALUES (4, '202410004', '74567890', 'Carlos Alberto', 'Mamani Flores', 'carlos.mamani@upeu.edu.pe', 0, 1, CURRENT_TIMESTAMP);
INSERT INTO estudiantes (id, codigo, dni, nombres, apellidos, email, estado, carrera_id, fecha_creacion)
VALUES (5, '202410005', '75678901', 'Rosa', 'Salazar Peña', 'rosa.salazar@upeu.edu.pe', 1, 3, CURRENT_TIMESTAMP);
INSERT INTO estudiantes (id, codigo, dni, nombres, apellidos, email, estado, carrera_id, fecha_creacion)
VALUES (6, '202410006', '76789012', 'Miguel', 'Vargas Soto', 'miguel.vargas@upeu.edu.pe', 1, 2, CURRENT_TIMESTAMP);

-- Mantiene libres los siguientes valores generados por JPA tras usar ID fijos.
ALTER TABLE carreras MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE cursos MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE estudiantes MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE matriculas MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE detalle_matriculas MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

COMMIT;
