spring:
  application:
    name: MatriculaBackend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false
  jackson:
    time-zone: America/Lima

matricula:
  costo-credito: 120.00
